# MacPorts
# export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# Get colors in manual pages
export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode – red
export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode – bold, magenta
export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode – yellow
export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode – cyan


# if [ “$TERM” != “dumb” ]; then
#    export LS_OPTIONS=‘–color=auto’
#    eval </span>dircolors ~/.dir_colors<span class="sb">
# fi

# Functions

## Change directory to the current Finder directory
# cdf() {
#    target=`osascript -e 'tell application "Finder" to if (count of Finder windows) > 0 then get POSIX path of (target of front Finder window as text)'`
#    if [ "$target" != "" ]; then
#        cd "$target"; pwd
#    else
#        echo 'No Finder window found' >&2
#    fi
# } 
